### ISSUE TITLE
simulatorのfpu演算(itof,ftoi,floor)

### ISSUE THREAD

**Issue by nonaka-is** [cpuex2015-group1/Cartelet#2]
itof,ftoi,floorのC実装を Cartelet/core/fpu/C に置いたので、opecodeが決まり次第、実装をお願いします。
なお、x87演算は
itof: output.f = (floor)input
ftoi: output = (int32_t)roundf(input.f)
floor: output.f = floor(input.f)
としてください。

**Comment by makoto0** [comment]
組み込みました。
