### ISSUE TITLE
アセンブラ・シミュレータの2nd opcode対応

### ISSUE THREAD

**Issue by nekketsuuu** [cpuex2015-group1/Cartelet#4]
2nd ISA
https://www.evernote.com/shard/s45/sh/7f461e9a-5783-4dc7-9976-a27249823e6b/4b4c9816fb046827

branchのeq/neq/lt/leはこの順番に00〜11

**Comment by nekketsuuu** [comment]
汚くしてごめんなさい
なんかうまく複数人同時に割り当てられないのでこのままにしておきます

**Comment by makoto0** [comment]
シミュレータのopcodeを設定しました。

**Comment by nekketsuuu** [comment]
アセンブラも2nd命令セットに対応しました。
