### ISSUE TITLE
シミュレータを強制終了させたときに統計情報を表示する

### ISSUE THREAD

**Issue by nekketsuuu** [cpuex2015-group1/Cartelet#9]
SIGINTに対してのハンドラがあると嬉しいです。

具体的には、今なんか無限ループしてそうだな〜〜〜ってときに、rin -rだとどこを実行していてどういう値になっているときに無限ループなのか分からず、rin -sだとpoffだと意味なくてponだとI/Oに時間がかかってなかなか当該部分に達さなかったりするので、そういうデバッグの時間が短縮できると思いました。

急ぎません。

**Comment by makoto0** [comment]
遅くなってごめんなさい。
今更ですが実装しました。

**Comment by nekketsuuu** [comment]
[補足]
シグナルハンドラ内では非同期シグナルセーフな関数しか使えない(特に、printfは使えない)ので、[これとか](http://d.hatena.ne.jp/yupo5656/20060114/p1)、[これとか](http://alpha-netzilla.blogspot.jp/2014/10/signal.html)などの方法で回避する必要があります。
